title: Marao Dashboard
description: A modern yet simple UI for your Home Assistant dashboard
theme: just-the-docs
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"

url: https://diogomrpr.github.io
baseurl: /MaraoDashboard

# Color scheme supports "light" (default) and "dark"
color_scheme: marao_dashboard

footer_content: _includes/footer_custom.html

callouts:
  warning:
    title: Warning
    color: red

# Aux links for the upper right navigation
aux_links:
  "Marao Dashboard on GitHub":
    - "https://github.com/diogomrpr/MaraoDashboard"
