name: Validate with hassfest

on:
  push:
    paths:
      - ".github/workflows/hassfest.yml"
      - "custom_components/**"
  pull_request:
    paths:
      - ".github/workflows/hassfest.yml"
      - "custom_components/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
